spring:
  datasource:
    url: jdbc:mysql://192.168.2.128:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  context-path: /sell

#logging:
#  pattern:
#    console: "%d-%msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug
